### ISSUE TITLE
Unable to install 4.10 "The requested manifest (..) did not provide module manifest data"

### ISSUE THREAD

**Issue by DawidIzydor** [Drental/foundryvtt-pf2e-f-is-for-flatfooted#12]
Foundry v. 10.285. The module is fully uninstalled. Go into Add-ons, click "Install Module", find "pF2E Keybind Menagerie", click Install.
![image](https://user-images.githubusercontent.com/30767613/190366108-5950aad5-5cf2-45b7-b6b0-0bef663f918c.png)

Expected outcome: the module installs
Actual outcome: installation error 
![image](https://user-images.githubusercontent.com/30767613/190366378-d487508d-ebe3-4c2f-aef5-cebb1aa8607e.png)

In the console
`Error: Unable to load valid module manifest data from "https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/releases/download/4.10.0/module.json"
The requested manifest at "https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/releases/download/4.10.0/module.json" did not provide module manifest data.
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1620)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)
error @ setup.js:292
(anonymous) @ setup.js:345
async function (async)
(anonymous) @ setup.js:334
installPackage @ setup.js:276
_onClickPackageInstall @ setup.js:1047
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2`

**Comment by DawidIzydor** [comment]
Seems to be fixed in 4.10.1, you released a hotfix just as I was creating this ticket, nice
